### ISSUE TITLE
Special characters in URL

### ISSUE THREAD

**Issue by luukdv** [trendwerk/redirects#4]
When the source URL contains a character like `©` or `™`, the redirect doesn't work. Don't know if this is an easy fix / worth the time.

**Comment by haroldangenent** [comment]
@luukdv This is fixed in https://github.com/trendwerk/redirects/commit/de02d401334f0a6a832d15bd75aa520ba558d21f.

However, since I do not know exactly what effect this has on other types of redirects, it needs some testing before I release it. Could you test this thoroughly and see if any other redirects fail that used to work before?

**Comment by haroldangenent** [comment]
@luukdv Thanks for testing.
