### ISSUE TITLE
DB error

### ISSUE THREAD

**Issue by luukdv** [trendwerk/redirects#6]
The plugin seems to cause the following error:

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF' at line 1`

Tested without any other plugins active, except debugging ones.

**Comment by haroldangenent** [comment]
@luukdv Errors are partially fixed (they were interpretence problems of `dbDelta`), but it's impossible to fix them all because of this code in `dbDelta`: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/upgrade.php#L2211-L2213.

Errors get suppressed, but still get printed when you use Debug Bar for example.
